# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9482de47309c48bedd9005c14724f9ffea514260386d4f55b797809a50d6835859d07648058da2e962f0f8a2c49b31f7837544224d659597ab615b95c8d815d

test:
  secret_key_base: 4bbe9693bfcb21215a24b178876021dbda3ff6da735e3d550953892fe754cdde7fc97415bb35ff935f140a9e6da3c8ce3cfaeea374799f496caf4f100955b4d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
